### ISSUE TITLE
[Bug]:  I got a black screen Battle.net launcher after upgraded to 1.0.0 and GPTK beta 1.0.2

### ISSUE THREAD

**Issue by larryisthere** [IsaacMarovitz/Whisky#198]
### Description

<img width="1512" alt="image" src="https://github.com/IsaacMarovitz/Whisky/assets/271518/ae9f8c7c-698f-4ef6-8529-736b8a67a234">

### Steps to reproduce

1. whisky 0.3.1 + Ventura works
2. upgrade to whisky 1.0.0 and GPTK beta 1.0.2 on Ventura doesn't work (black screen)
3. upgrade to Sonama still doesn't work (black screen)

### Expected behaviour

Show the UI as whisky 0.3.1 + Ventura does.

### Logs

```bash
Whisky Version: 1.0.0
Date: 2023/7/3, 22:48:33
macOS Version: Version 14.0 (Build 23A5276g)
Bottle Name: Diablo IV
Wine Version: 7.7.0
Wine Binary Version: 4
Windows Version: win10
Bottle URL: /Users/larryisthere/Library/Containers/com.isaacmarovitz.Whisky/Bottles/Diablo IV

Arguments: start C:\Program Files (x86)\Diablo IV\Diablo IV Launcher.exe 

Launched Wine (6201)
rface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
		VK_KHR_multiview v1
		VK_KHR_portability_subset v1
		VK_KHR_push_descriptor v2
		VK_KHR_relaxed_block_layout v1
		VK_KHR_sampler_mirror_clamp_to_edge v3
		VK_KHR_sampler_ycbcr_conversion v14
		VK_KHR_separate_depth_stencil_layouts v1
		VK_KHR_shader_draw_parameters v1
		VK_KHR_shader_float_controls v4
		VK_KHR_shader_float16_int8 v1
		VK_KHR_shader_subgroup_extended_types v1
		VK_KHR_spirv_1_4 v1
		VK_KHR_storage_buffer_storage_class v1
		VK_KHR_surface v25
		VK_KHR_swapchain v70
		VK_KHR_swapchain_mutable_format v1
		VK_KHR_timeline_semaphore v2
		VK_KHR_uniform_buffer_standard_layout v1
		VK_KHR_variable_pointers v1
		VK_EXT_buffer_device_address v2
		VK_EXT_debug_marker v4
		VK_EXT_debug_report v10
		VK_EXT_debug_utils v2
		VK_EXT_descriptor_indexing v2
		VK_EXT_external_memory_host v1
		VK_EXT_fragment_shader_interlock v1
		VK_EXT_hdr_metadata v2
		VK_EXT_host_query_reset v1
		VK_EXT_image_robustness v1
		VK_EXT_inline_uniform_block v1
		VK_EXT_memory_budget v1
		VK_EXT_metal_objects v1
		VK_EXT_metal_surface v1
		VK_EXT_pipeline_creation_cache_control v3
		VK_EXT_post_depth_coverage v1
		VK_EXT_private_data v1
		VK_EXT_robustness2 v1
		VK_EXT_sample_locations v1
		VK_EXT_scalar_block_layout v1
		VK_EXT_separate_stencil_usage v1
		VK_EXT_shader_atomic_float v1
		VK_EXT_shader_stencil_export v1
		VK_EXT_shader_viewport_index_layer v1
		VK_EXT_subgroup_size_control v2
		VK_EXT_surface_maintenance1 v1
		VK_EXT_swapchain_colorspace v4
		VK_EXT_swapchain_maintenance1 v1
		VK_EXT_texel_buffer_alignment v1
		VK_EXT_texture_compression_astc_hdr v1
		VK_EXT_vertex_attribute_divisor v3
		VK_AMD_gpu_shader_half_float v2
		VK_AMD_negative_viewport_height v1
		VK_AMD_shader_image_load_store_lod v1
		VK_AMD_shader_trinary_minmax v1
		VK_IMG_format_pvrtc v1
		VK_INTEL_shader_integer_functions2 v1
		VK_GOOGLE_display_timing v1
		VK_MVK_macos_surface v3
		VK_MVK_moltenvk v37
		VK_NV_fragment_shader_barycentric v1
		VK_NV_glsl_shader v1
07e0:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
[mvk-info] Created 3 swapchain images with initial size (106, 2) and contents scale 1.0 for screen Built-in Retina Display.
03e0:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
[mvk-info] Created 3 swapchain images with initial size (1518, 916) and contents scale 1.0 for screen Built-in Retina Display.
```

### What version of Whisky are you using?

1.0.0

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by jipiboily** [comment]
Same here. But I enabled DXVK, and Battle.net launches, but not D4 (no GPU error).

**Comment by loudywen** [comment]
same here

**Comment by assc-ryan** [comment]
Same issue fro my site
Mac M1
Whisky 1.0.0

**Comment by vinhtq115** [comment]
Same issue. Battle.net client worked fine with 0.3.1 + GPTK 1.0.2.

**Comment by devantler** [comment]
I fixed it by deleting the Libraries folder in `~/Library/Application Support/Whisky`, and using these settings:

![image](https://github.com/IsaacMarovitz/Whisky/assets/26203420/17a0c09d-cbb4-4263-88fb-8b492b9b53ac)

**Comment by loudywen** [comment]
No GPU error

**Comment by RussianLioN** [comment]
> Same issue from my site Mac M1 Whisky 1.0.0
Same issue from my site
Mac M2
Whisky 1.0.0
GPTK 1.0.2

**Comment by slider1202** [comment]
> 

Sorry  how can I locate to ~/Library/Application Support/Whisky?

**Comment by vinhtq115** [comment]
A temporary way to fix this is to revert to 0.3.1, open Battle.net and turn off hardware acceleration. After Whisky updated to 1.0.0, the client will show up.

**Comment by devantler** [comment]
> > 
> 
> Sorry how can I locate to ~/Library/Application Support/Whisky?

1. Open finder
2. Click `Go>Go to folder` in the menu bar
3. Copy paste the path into the window, and enter.

**Comment by VingtSix** [comment]
> No GPU error

Same

**Comment by dgarte** [comment]
Same issue with GPTK 1 & GPTK 1.0.2 and Whisky 1.0

With DXVK active Battle.net is visible, but game shows - No GPU found issue -

Without DXVK, Battle.net is not visible

**Comment by OmniSwapLabs** [comment]
> Same issue with GPTK 1 & GPTK 1.0.2 and Whisky 1.0
> 
> With DXVK active Battle.net is visible, but game shows - No GPU found issue -
> 
> Without DXVK, Battle.net is not visible

Same here

**Comment by larryisthere** [comment]
> 

[Same here](https://github.com/IsaacMarovitz/Whisky/issues/198#issuecomment-1618979646) works for me.

**Comment by dolidolih** [comment]
1. Right click the battlenet tray icon and click settings
2. Uncheck "Use browser hardware acceleration"
3. Click Restart
4. Kill all bottles
5. Run battlenet again

**Comment by kartarion** [comment]
> Same issue with GPTK 1 & GPTK 1.0.2 and Whisky 1.0
> 
> With DXVK active Battle.net is visible, but game shows - No GPU found issue -
> 
> Without DXVK, Battle.net is not visible

#194

> To fix the black screen run the launcher with DXVK and disable browser hardware acceleration:
> 
> ![image](https://user-images.githubusercontent.com/26203420/250637288-bb79f115-6662-4fc9-bddc-76ff810f3908.png)
> 
> Then if it is not working yet try deleting the Libraries folder in `~/Library/Application Support/Whisky`, and using these settings:
> 
> ![image](https://user-images.githubusercontent.com/26203420/250637160-17a0c09d-cbb4-4263-88fb-8b492b9b53ac.png)
> 
> With these changes I am now able to run the launcher with DX12, and launch and play the game.

Checked again, after deleting again the folder in App Support, works again. Thanks!

**Comment by sethmackay** [comment]
> REVISED! FIXED AFTER GOING BACK AND TURNING OFF DXVK AFTER DISABLING THE BROWSER HARDWARE ACCELERATION AND DELETING THE APP SUPPORT FILES.

How do you delete the app support files? which files?

**Comment by DCGlc** [comment]
help！

After I entered battle.net and tried to open diablo 4, it was prompted to log in as an administrator and try again. It was very strange. After I upgraded to whiskey 1.0, I ran the game normally once, and after logging out for a while, this prompt appeared. causing the game not to run.

How do I run whiskey installed windows software as administrator? After all, I can't right-click on the software icon to select this function.

I reinstalled battle.net in whiskey 0.3, and then copied the diablo 4 folder. Unfortunately, the problem is still the same. Even when I scan the game, this problem will appear halfway through. I really have to download it again Game yet?

**Comment by IsaacMarovitz** [comment]
Seems issue is resolved by turning off hardware acceleration

**Comment by Madoc439** [comment]
I am still getting the "No GPU" error.  Can you point me to the right directory to remove to test?  I can't seem to find the right one.

**Comment by DCGlc** [comment]
I reinstalled whisky1.0, battlenet, diablo4, the same settings as whisky0.3, but I enter diablo4 will flash back, or can not enter the game, or enter the game and report an error...

**Comment by DCGlc** [comment]
I reinstalled whiskey0.31 and battlenet, and when I entered the game, it still crashed. When I entered the game again, I was prompted that there was a problem with the GPU, and then I would be prompted to require administrator privileges. It seems that the diablo file is damaged again, and I can no longer run it. The game is over.

**Comment by schischa** [comment]
> I am still getting the "No GPU" error. Can you point me to the right directory to remove to test? I can't seem to find the right one.

I experienced the same issue and realised that GPTK wasn't installed anymore. Check the setup in whisky and reinstall GPTK if it's not present. That fixed it for me. Also make sure to run the most recent version of whisky, as there was a problem with GPTK Beta 4 and it couldnt be installed.

**Comment by dreamtheater1984** [comment]
<img width="1512" alt="Screenshot 2023-12-02 alle 08 40 38" src="https://github.com/Whisky-App/Whisky/assets/6421313/4f87f08d-11f6-42cb-b5f7-a87c994592ed">
This is my situation: Blue Screen.
Mac M1
Whisky  2.2.1 
If i try to start with active dxvk it doesn't start. 
Can someone help me?

**Comment by vinhtq115** [comment]
> <img alt="Screenshot 2023-12-02 alle 08 40 38" width="1512" src="https://private-user-images.githubusercontent.com/6421313/287429500-4f87f08d-11f6-42cb-b5f7-a87c994592ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDM1ODYsIm5iZiI6MTcwMTUwMzI4NiwicGF0aCI6Ii82NDIxMzEzLzI4NzQyOTUwMC00Zjg3ZjA4ZC0xMWY2LTQyY2ItYjVmNy1hODdjOTk0NTkyZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDc0ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjRiM2RkYWM0MDFhZTFlMjkyMTM1M2UwMTk3MGQ1YmM0OTZjMDJmNjU1YzEwZjI2ZjE2MGVmODY4YzI5YjdmYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uuKr5W77Oi2BRJjL_NxFXxkSrwtS4VmS1jMmsA1XW0E"> This is my situation: Blue Screen. Mac M1 Whisky 2.2.1 If i try to start with active dxvk it doesn't start. Can someone help me?

Try disabling Hardware Acceleration in Battle.net settings

**Comment by dreamtheater1984** [comment]
Yes, among the thousand tests I had managed to disable it.
Now to do a test I rehabilitated him and I can no longer start Battlenet.
<img width="542" alt="Screenshot 2023-12-02 alle 08 58 05" src="https://github.com/Whisky-App/Whisky/assets/6421313/8827370a-92e5-43e0-9ffe-ae83833d3b4c">

**Comment by vinhtq115** [comment]
> Yes, among the thousand tests I had managed to disable it. Now to do a test I rehabilitated him and I can no longer start Battlenet. <img alt="Screenshot 2023-12-02 alle 08 58 05" width="542" src="https://private-user-images.githubusercontent.com/6421313/287430386-8827370a-92e5-43e0-9ffe-ae83833d3b4c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MDQ1MDksIm5iZiI6MTcwMTUwNDIwOSwicGF0aCI6Ii82NDIxMzEzLzI4NzQzMDM4Ni04ODI3MzcwYS05MmU1LTQzZTAtOWZmZS1hZTgzODMzZDNiNGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMDgwMzI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDllNjFiY2JkMGU3MmNiMDMxOTdkMGY3MzExOWQzNTZhMDk1MjljMDkyMTg3ODYzMDFjOGM2ZmVhZDM0MDA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YrN4DcKVND5wVI67dTe0E5MPcF_Q3D9C1PyshCpdbE0">

Didn't notice that you mentioned DXVK is turned on. Mine works fine but it was deactivated. Here is my bottle config. Hardware acceleration is turned off in Battle.net.

<img width="816" alt="image" src="https://github.com/Whisky-App/Whisky/assets/34190240/90adb1eb-7f8b-4cd6-8758-c39191af606d">

**Comment by dreamtheater1984** [comment]
Now DXVK is off and this is my config

<img width="923" alt="Screenshot 2023-12-02 alle 09 07 03" src="https://github.com/Whisky-App/Whisky/assets/6421313/ec59099c-4ac5-4e79-9299-571c6a36838b">

**Comment by dreamtheater1984** [comment]
Whisky Version: 2.2.1
Date: 2023-12-02T08:18:38Z
macOS Version: 14.2.0

Bottle Name: Battlenet
Bottle URL: /Users/silviopasquali/Downloads/DDCC81BD-1C46-49B3-9AEF-C666EC773A67

Wine Version: 7.7.0
Windows Version: win10
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/silviopasquali/Downloads/DDCC81BD-1C46-49B3-9AEF-C666EC773A67/drive_c/Program Files (x86)/Battle.net/Battle.net Launcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    WINEDEBUG = "fixme-all";
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/silviopasquali/Downloads/DDCC81BD-1C46-49B3-9AEF-C666EC773A67";
}

msync: bootstrapped mach port on wine-1ac57f-msync.
msync: up and running.
0068:err:module:open_builtin_so_file failed to load .so lib "/Users/silviopasquali/Library/Application Support/com.isaacmarovitz.Whisky/Libraries/Wine/lib/wine/x86_64-unix/wineusb.sys.so"
0068:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
00e0:err:winediag:ntlm_check_version ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
00e0:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
011c: thread_get_state failed on Apple Silicon - faking zero debug registers
00e0: thread_get_state failed on Apple Silicon - faking zero debug registers
0168: thread_get_state failed on Apple Silicon - faking zero debug registers
0178: thread_get_state failed on Apple Silicon - faking zero debug registers
0174: thread_get_state failed on Apple Silicon - faking zero debug registers
01a0: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] MoltenVK version 1.2.3, supporting Vulkan version 1.2.243.
	The following 89 Vulkan extensions are supported:
		VK_KHR_16bit_storage v1
		VK_KHR_8bit_storage v1
		VK_KHR_bind_memory2 v1
		VK_KHR_buffer_device_address v1
		VK_KHR_copy_commands2 v1
		VK_KHR_create_renderpass2 v1
		VK_KHR_dedicated_allocation v3
		VK_KHR_depth_stencil_resolve v1
		VK_KHR_descriptor_update_template v1
		VK_KHR_device_group v4
		VK_KHR_device_group_creation v1
		VK_KHR_driver_properties v1
		VK_KHR_dynamic_rendering v1
		VK_KHR_external_fence v1
		VK_KHR_external_fence_capabilities v1
		VK_KHR_external_memory v1
		VK_KHR_external_memory_capabilities v1
		VK_KHR_external_semaphore v1
		VK_KHR_external_semaphore_capabilities v1
		VK_KHR_fragment_shader_barycentric v1
		VK_KHR_get_memory_requirements2 v1
		VK_KHR_get_physical_device_properties2 v2
		VK_KHR_get_surface_capabilities2 v1
		VK_KHR_imageless_framebuffer v1
		VK_KHR_image_format_list v1
		VK_KHR_maintenance1 v2
		VK_KHR_maintenance2 v1
		VK_KHR_maintenance3 v1
	01e8: thread_get_state failed on Apple Silicon - faking zero debug registers
01f8: thread_get_state failed on Apple Silicon - faking zero debug registers
[mvk-info] Created VkInstance for Vulkan version 1.1.0, as requested by app, with the following 2 Vulkan extensions enabled:
		VK_KHR_surface v25
		VK_EXT_metal_surface v1
0260: thread_get_state failed on Apple Silicon - faking zero debug registers
0200:err:kerberos:kerberos_LsaApInitializePackage no Kerberos support, expect problems
0284: thread_get_state failed on Apple Silicon - faking zero debug registers
0224: thread_get_state failed on Apple Silicon - faking zero debug registers
0164: thread_get_state failed on Apple Silicon - faking zero debug registers
017c: thread_get_state failed on Apple Silicon - faking zero debug registers
01a8: thread_get_state failed on Apple Silicon - faking zero debug registers
02a0: thread_get_state failed on Apple Silicon - faking zero debug registers
036c: thread_get_state failed on Apple Silicon - faking zero debug registers
0374: thread_get_state failed on Apple Silicon - faking zero debug registers

**Comment by jeffnguyener** [comment]
> Now DXVK is off and this is my config but. Hardware acceleration is on and i can't enter in Battle.net.
> 
> <img alt="Screenshot 2023-12-02 alle 09 07 03" width="923" src="https://private-user-images.githubusercontent.com/6421313/287430779-ec59099c-4ac5-4e79-9299-571c6a36838b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1Mjk5MDIsIm5iZiI6MTcwMTUyOTYwMiwicGF0aCI6Ii82NDIxMzEzLzI4NzQzMDc3OS1lYzU5MDk5Yy00YWM1LTRlNzktOTI5OS01NzFjNmEzNjgzOGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDJUMTUwNjQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTM1MDFmMzFiMTBjYzJkNGI1NzRmOWQwOWQwMmIzMzJmNWRjMGViNDdkYWYwODRjZjU3NTQ5NWI1MWNiYmRhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QPx-BG43o1jtHi9V2ZM_mtAD80K8mqfshIDr_g_-tjQ">

I am in the same boat. With DXVK on, it doesn't even launch the Blizzard launcher, with it off it does but with a blank screen.

**Comment by jeffnguyener** [comment]
This might be a temporary fix, just as long as you have the previous version of Battle.net.14494 folder

[https://github.com/Whisky-App/Whisky/issues/666](url)

Open C: Drive -> Program Files (x86) -> Battle.net and deleted Battle.net.14542 folder

**Comment by MeCorvus** [comment]
Works, thanks! But it's very temporary as it involves deleting it every time.
